[package]
name = "abridged-certs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
simple-error = "0.3.0"

[dev-dependencies]
hex = "0.4.3"